web-deploy-1/web-deploy-1/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_deploy_1.Models;
using web_deploy_1.ViewModels;

namespace web_deploy_1.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            var essam = new Models.Employee();
            essam.emp_id = 654;
            essam.emp_name = "EssamNasser";

            ViewData["Score"] ="Good";
            return View(essam);
        }

        public ActionResult About()
        {
            //ViewData["MyName"] = "LOLO";
            //ViewData["MyScore"] = 34;


            return View();

        }


        public ActionResult our_service()
        {
            return View();
        }


        public ActionResult return_text()
        {
            return Content("This is just text");
            //return HttpNotFound();
            //return EmptyResult();
            //return RedirectToAction("Action Name","Controller Name",new{page=1,sortBy="Name"});
                
        }
        public ActionResult dummy1()
        {
            return RedirectToAction("return_text", "Employess", new { page = 1, sortBy = "Name" });

        } 
        
        public ActionResult edit_t(int id)
        {
            // use the link http://localhost/Employee/edit_t/5
            return Content("Id id :" + id);
        }

        public ActionResult edit_R(string V)
        {
            //Use http://localhost/Employee/edit_R/essam  ==dont work
            // OR http://localhost/employee/edit_R?V=essam
            return Content(V);
        }


        public ActionResult List_emp(int? pageIndex,string SortName)
        {
            if (!pageIndex.HasValue) { pageIndex = 1; }
            if (String.IsNullOrWhiteSpace(SortName)) { SortName = "name"; }

            return Content(String.Format("PageIndex{0} SortNAme{1}",pageIndex, SortName));
        }



        public ActionResult send_data()
        {
            ViewData["name"] = "Essam Mohamady";
            ViewData["id"] = 232323;
            ViewData["Age"] = 23;

            return View();
        }




        public ActionResult list_employee()
        {
           Employee emp1 = new Employee() {emp_id=2323,emp_name="Essam Nasser" };
            Employee emp2 = new Employee() { emp_id = 232, emp_name = "Nibrass Mahdi" };
            Employee emp3 = new Employee() { emp_id = 4343, emp_name = "Jafer Essam Nasser" };
            Employee emp4 = new Employee() { emp_id = 7623, emp_name = "Aya and Mohammed" };

            var Emps = new List<Employee>();
            Emps.Add(emp1); Emps.Add(emp3); Emps.Add(emp3); Emps.Add(emp4);

            return View(Emps); 
            
        }


        public ActionResult return_emp_obj()
        {

            var M = new Employee() { emp_id = 898, emp_name = "Returne 1 object" };
            
            return View(M);
        }



        public ActionResult return_two_objects()
        {


            Employee emp1 = new Employee() { emp_id = 2323, emp_name = "Essam Nasser" };
            Employee emp2 = new Employee() { emp_id = 232, emp_name = "Nibrass Mahdi" };
            Employee emp3 = new Employee() { emp_id = 4343, emp_name = "Jafer Essam Nasser" };
            Employee emp4 = new Employee() { emp_id = 7623, emp_name = "Aya and Mohammed" };


            var Emps = new List<Employee>();
            Emps.Add(emp1); Emps.Add(emp3); Emps.Add(emp3); Emps.Add(emp4);


            Dep dep1 = new Dep() { dep_id = 12, dep_name = "Information" };


            Emp_by_Dep Obj = new Emp_by_Dep();
            Obj.department = dep1;
            Obj.Employees = Emps;


            return View(Obj);
        }


    }
}

web-deploy-1/web-deploy-1/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using web_deploy_1.Models;

namespace web_deploy_1.Controllers
{
    public class MovieController : Controller

    {

        //Database initialization
        ApplicationDbContext Dbase = new ApplicationDbContext();



        // GET: Movie
        public ActionResult Index()

        {
            Movie mov1 = new Movie { Id = 12, Title = "Star War" };
            Movie mov2 = new Movie { Id = 13, Title = "Star War1" };
            Movie mov3 = new Movie { Id = 14, Title = "Star War2" };

            var Movies = new List<Movie>();
            Movies.Add(mov1); Movies.Add(mov2); Movies.Add(mov3);

            var vewresult = new ViewResult();

            //ViewBag.Movies = Movies;
            //ViewData["Movies"] = Movies;
            return View(Movies);
        }




        public ActionResult Index2()
        {
            var Movies = Dbase.Movies.Include(p => p.Genre).ToList();
            return View(Movies);

        }


        //Action for add form
        public ActionResult new_movie()
        {

            return View();
        }


        public ActionResult Details(int id)
        {
            var Movie = Dbase.Movies.Include(p => p.Genre).SingleOrDefault(p => p.Id == id);

            return View(Movie);
        }


    }
}

web-deploy-1/web-deploy-1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

web-deploy-1/web-deploy-1/Views/Shared/_MVCPractice.cshtml
<div style="display:flex;flex-direction:column;flex-wrap:wrap">

    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("Try Text", "return_text", "Employee")

        this actionresult called return_text() in Employess controllers and use contents() function
    </div>
    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("Click Here", "dummy1", "Employee")
    </div>

    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("send integer", "edit_T", "Employee")
        this actionresult called edit_T it recieved <span style="color:blue">(int id)</span>
        <br />
        because it<span style="font-weight:600">reseving</span> we should url
        <br />
        localhost/Employee/edit_t?id=4
        </br>
        because the name of variable is id that matched the Rout Map rule
        </br>
        we can also write this localhost/Employee/edit_t/4
    </div>
    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("send string", "edit_R", "Employee")

        ActionResult called edit_R it recieving (string v)
        we call localhost/employee/edit_r?v=essam
    </div>


    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("LIST", "List_emp", "Employee")
        ActionResult List_emp, recieve 2 variables if they are null,the have default values
    </div>


    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("send dataview", "send_data", "Employee")
        ActionResult uses ViewData dictionary object to pass 3 variables

    </div>


    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("Return Employee", "return_emp_obj", "Employee")
        ActionResult returns ONE object

    </div>


    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("Return Employee List", "list_employee", "Employee")
        ActionResult returns List of objects

    </div>


    <div style="background-color:burlywood;color:white">
        @Html.ActionLink("Return Employee and Dep", "return_two_objects", "Employee")
        ActionResult returns TWO of objects

    </div>



</div>

web-deploy-1/web-deploy-1/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Movies(List)", "Index", "Movie")</li>
                <li>@Html.ActionLink("Movies(DB-all)","Index2","Movie")</li>
                <li>@Html.ActionLink("Customers(List)", "Index", "Customer")</li>
                <li>@Html.ActionLink("CustomersAll(Db)", "return_Db_all", "Customer")</li>
                <li>@Html.ActionLink("CustomersSingle(Db)", "return_Db_Single", "Customer")</li>
               
                <li></li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>